version: "3.7"
services:
  dbservice:
    container_name: dbservice
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: notes_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - springserv

  appservice:
    build:
      context: ./
    depends_on:
      - dbservice
    restart: always
    environment:
      MYSQL_HOST: dbservice
      MYSQL_USER: root
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: notes_db
    ports:
      - "8000-8999:8080"
    networks:
      - springserv

networks:
  springserv:
    driver: bridge



