version: '3'
services:
  dbservice:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - springserv

  appservice:
    build: ./
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/note_db?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8085:9292"
    networks:
      - springserv

networks:
  springserv: