version: '3.8'
services:

  dbservice:
    container_name: dbservice
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - springserv

  db_seeder:
    image: mysql:latest
    restart: always
    volumes:
      - ./db.sql:/db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: "root"
    entrypoint: [ "bash", "-c", "sleep 5 && mysql --user=root --host=dbservice --port=3306 notes_db < /resources/db/migration/db.sql && exit" ]
    depends_on:
      - dbservice

  appservice:
    build:
      context: ./
    depends_on:
      - dbservice
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:mysql://dbservice:3306/notes_db
    ports:
      - "8080:8080"
    networks:
      - springserv

networks:
  springserv:
    name: springserv
