version: '3'
services:
  dbservice:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - springserv

  appservice:
    build: ./
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/note_db?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8085:9292"
    networks:
      - springserv

networks:
  springserv: