version: '3.7'
services:
  dbservice:
    container_name: dbservice
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - springserv

  appservice:
    build: ./
    depends_on:
      - dbservice
    environment:
      spring.datasource.url: jdbc:mysql://dbservice:3308/notes_db?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
#      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    ports:
      - "8085:9292"
    networks:
      - springserv

networks:
  springserv:
