version: '3.8'
services:

  dbservice:
    container_name: dbservice
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    volumes:
      - ./MySQL:/docker-entrypoint-initdb.d
    networks:
      - springserv

  # db_seeder:
  #   image: mysql:latest
  #   volumes:
  #     - "./data:/var/lib/mysql"
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  #     MYSQL_ROOT_PASSWORD: "root"
  #   entrypoint: [ "bash", "-c", "sleep 10 && mysql --user=root --host=dbservice --port=3306 notes_db < data.sql && exit" ]
  #   depends_on:
  #     - dbservice

  appservice:
    build:
      context: ./
    depends_on:
      - dbservice
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://dbservice:3306/notes_db
    ports:
      - "8080:8080"
    networks:
      - springserv

networks:
  springserv:
    name: springserv
