version: '3.8'
services:

  dbservice:
    container_name: dbservice
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    ports:
      - "3307:3306"
    volumes:
      - /MySQL:/docker-entrypoint-initdb.d
      - /data/mysql
    networks:
      - springserv


  appservice:
    build:
      context: ./
    depends_on:
      - dbservice
    restart: always
    volumes:
      - /app/springboot-app
    ports:
      - "8080:8080"
    networks:
      - springserv

networks:
  springserv:
    name: springserv
